//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBAManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PositionName()
        {
            this.PositionOfPlayer = new HashSet<PositionOfPlayer>();
        }
    
        public int PositionID { get; set; }
        public string Name { get; set; }
        public string Abbr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PositionOfPlayer> PositionOfPlayer { get; set; }
    }
}
